### ISSUE TITLE
rgb to hex python bug

### ISSUE THREAD

**Issue by aiqojo** [DocDomergue/Open-Source-Project#4] opened 2023-03-21 14:44 UTC
Invalid hex values are obtained using the rgb_to_hex.py script.

## To reproduce
1. You can enter an rgb value with g > 255 and it won't cap it to 255, only to 256. This is outside of the range that would be considered valid, but the program still accepts it.

2. Also, it is impossible to get a perfect black if a value for r < 1 is inputted. The code seems to but the floor for r values at 1, instead of 0.

## Additional Information
Windows 10 64-bit
Firefox 111.0 64-bit

## Solutions
1. Change value from 256 to 255.
2. Change value from 1 to 0.

This is a perfectly reproducible, medium priority, low impact bug. This can occur every time following the steps, but is likely not to affect many users as it requires putting in rgb values outside of the valid range. Though this should be fixed as soon as possible.

**Comment by DocDomergue** [comment] 2023-03-21 14:54
Investigating now

**Comment by DocDomergue** [comment] 2023-03-21 15:00
Discovered the bugs mentioned in the report, and implemented recommended fixes. Also discovered unrelated logical issue, which has now been fixed.

**Comment by DocDomergue** [comment] 2023-03-21 15:02
Testing confirms issue has been resolved and the program appears to be fully working as intended. Closing Issue.

**Closed as completed by DocDomergue** 2023-03-21 15:02 UTC
Labels: bug
